### PR TITLE
Code highlighting

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Work-in-progress for Code highlighing.

### CODE REVIEW

**Comment by TheNeikos** [comment]
Could you please add Pygments to the `requirements.txt` if #2 gets merged before?

**Comment by matthiasbeyer** [comment]
pygments is actually not used by pandoc, even if you use the pygments highlighting.

**Comment by TheNeikos** [comment]
Alright, well if you do end up using a python library, do add it please then

**Comment by matthiasbeyer** [comment]
Yep

**Comment by matthiasbeyer** [comment]
@TheNeikos Code highlighting works now. We might want to tweak some settings, and I will definitively rebase and squash here, but you are free to make suggestions now.

**Comment by TheNeikos** [comment]
You could add the classoption `twocolumn`

**Comment by matthiasbeyer** [comment]
You mean in the listings setup PR? How is this related?

**Comment by TheNeikos** [comment]
:tangerine: Well, it was a suggestion! But you are right, it's not related.

If the colors work I would merge.

**Comment by matthiasbeyer** [comment]
History rewritten. Feel free to merge.

**Pull request merged**
